(function(){
  const locations=[
    {
      id:'current-beijing-haidian',
      name:'北京市海淀区中关村南大街27号',
      shortName:'中关村南大街27号',
      city:'北京',
      district:'海淀区',
      region:'北京市海淀区',
      lat:39.9856,
      lng:116.3187,
      keywords:['北京','海淀','中关村','人大','当前位置','当前定位','中关村南大街']
    },
    {
      id:'beijing-aosen-south',
      name:'北京市朝阳区奥林匹克森林公园南门',
      shortName:'奥森南门',
      city:'北京',
      district:'朝阳区',
      region:'北京市朝阳区',
      lat:40.0183,
      lng:116.396,
      keywords:['北京','朝阳','奥森','奥林匹克森林公园','跑步','公园']
    },
    {
      id:'beijing-xiangshan-east',
      name:'北京市海淀区香山公园东门',
      shortName:'香山公园东门',
      city:'北京',
      district:'海淀区',
      region:'北京市海淀区',
      lat:39.9997,
      lng:116.1877,
      keywords:['北京','香山','海淀','爬山','徒步','香山公园']
    },
    {
      id:'beijing-pumch-east',
      name:'北京市东城区北京协和医院东院区',
      shortName:'协和医院东院区',
      city:'北京',
      district:'东城区',
      region:'北京市东城区',
      lat:39.9084,
      lng:116.4185,
      keywords:['北京','东城','协和','医院','陪诊']
    },
    {
      id:'guangzhou-tianhe-sports',
      name:'广州市天河区天河体育中心东门',
      shortName:'天河体育中心东门',
      city:'广州',
      district:'天河区',
      region:'广州市天河区',
      lat:23.1317,
      lng:113.3229,
      keywords:['广州','天河','体育中心','珠江新城','天河体育中心']
    },
    {
      id:'guangzhou-zhujiang',
      name:'广州市天河区珠江新城花城广场',
      shortName:'花城广场',
      city:'广州',
      district:'天河区',
      region:'广州市天河区',
      lat:23.1195,
      lng:113.3247,
      keywords:['广州','珠江新城','花城广场','天河','广州塔']
    },
    {
      id:'guangzhou-baiyun',
      name:'广州市白云区白云山南门',
      shortName:'白云山南门',
      city:'广州',
      district:'白云区',
      region:'广州市白云区',
      lat:23.1663,
      lng:113.2879,
      keywords:['广州','白云山','白云','爬山','户外']
    },
    {
      id:'huangshan-transfer',
      name:'黄山市黄山区汤口镇黄山风景区换乘中心',
      shortName:'黄山换乘中心',
      city:'黄山',
      district:'黄山区',
      region:'黄山市黄山区',
      lat:30.1318,
      lng:118.1729,
      keywords:['黄山','汤口','风景区','换乘中心','爬山','登山']
    },
    {
      id:'huangshan-north-gate',
      name:'黄山市黄山区黄山北大门停车场',
      shortName:'黄山北大门',
      city:'黄山',
      district:'黄山区',
      region:'黄山市黄山区',
      lat:30.1682,
      lng:118.1826,
      keywords:['黄山','北大门','停车场','黄山区','登山']
    },
    {
      id:'huangshan-tunxi',
      name:'黄山市屯溪区屯溪老街牌坊',
      shortName:'屯溪老街',
      city:'黄山',
      district:'屯溪区',
      region:'黄山市屯溪区',
      lat:29.7108,
      lng:118.3118,
      keywords:['黄山','屯溪','老街','屯溪老街']
    },
    {
      id:'shanghai-lujiazui',
      name:'上海市浦东新区陆家嘴中心绿地',
      shortName:'陆家嘴中心绿地',
      city:'上海',
      district:'浦东新区',
      region:'上海市浦东新区',
      lat:31.2374,
      lng:121.5004,
      keywords:['上海','浦东','陆家嘴','中心绿地']
    }
  ];

  const tasks=[
    {
      id:'cat-1',
      type:'cat',
      title:'上门喂猫｜1.5 小时｜海淀区',
      price:120,
      timeKey:'tomorrow',
      timeText:'明天 14:00',
      duration:'约1.5h',
      credit:92,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'张小花',
      locationName:'中关村南大街·科苑小区',
      lat:39.9893,
      lng:116.3301,
      search:['喂猫','猫','中关村','海淀','上门喂猫'].join(' ')
    },
    {
      id:'outdoor-1',
      type:'outdoor',
      title:'户外任务｜1 小时｜朝阳区',
      price:80,
      timeKey:'today',
      timeText:'今天 17:00',
      duration:'约1h',
      credit:88,
      statusClass:'urgent-status',
      statusText:'急单抢接',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'急单',
      tags:[],
      publisher:'李明',
      locationName:'奥林匹克森林公园南门',
      lat:40.0078,
      lng:116.3392,
      search:['陪跑','爬山','户外','奥森','公园','徒步'].join(' ')
    },
    {
      id:'health-1',
      type:'health',
      title:'健康陪诊｜3 小时｜海淀区',
      price:150,
      timeKey:'week',
      timeText:'周三 09:00',
      duration:'约3h',
      credit:95,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'王阿姨',
      locationName:'北医三院门诊楼',
      lat:39.9732,
      lng:116.3624,
      search:['陪诊','医院','北医三院','取药'].join(' ')
    },
    {
      id:'cat-2',
      type:'cat',
      title:'上门喂猫｜1 小时｜海淀区',
      price:95,
      timeKey:'today',
      timeText:'今天 20:30',
      duration:'约1h',
      credit:86,
      statusClass:'urgent-status',
      statusText:'即将截止',
      insuranceClass:'uninsured',
      insuranceText:'未购保险',
      badgeText:'',
      tags:[],
      publisher:'陈同学',
      locationName:'双榆树青年公寓',
      lat:39.9689,
      lng:116.3379,
      search:['喂猫','朝阳','公寓','晚间'].join(' ')
    },
    {
      id:'health-2',
      type:'health',
      title:'健康陪诊｜2 小时｜海淀区',
      price:130,
      timeKey:'tomorrow',
      timeText:'明天 10:00',
      duration:'约2h',
      credit:84,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'uninsured',
      insuranceText:'未购保险',
      badgeText:'',
      tags:[],
      publisher:'刘阿姨',
      locationName:'人民大学社区医院',
      lat:39.9753,
      lng:116.3022,
      search:['陪诊','社区医院','复诊','报告'].join(' ')
    },
    {
      id:'cat-3',
      type:'cat',
      title:'上门喂猫｜40 分钟/次｜海淀区',
      price:168,
      timeKey:'week',
      timeText:'周五 19:00',
      duration:'约40分钟/次',
      credit:90,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'乔女士',
      locationName:'知春路乐乎公寓',
      lat:39.9821,
      lng:116.3824,
      search:['喂猫','知春路','布偶猫','连单'].join(' ')
    },
    {
      id:'outdoor-2',
      type:'outdoor',
      title:'户外任务｜4 小时｜海淀区',
      price:180,
      timeKey:'week',
      timeText:'周六 08:00',
      duration:'约4h',
      credit:91,
      statusClass:'full',
      statusText:'已约满',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'周老师',
      locationName:'香山公园东门',
      lat:40.0028,
      lng:116.3894,
      search:['户外','爬山','香山','登山','陪同'].join(' ')
    },
    {
      id:'outdoor-3',
      type:'outdoor',
      title:'户外任务｜1.5 小时｜海淀区',
      price:118,
      timeKey:'today',
      timeText:'今天 21:00',
      duration:'约1.5h',
      credit:85,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'韩小姐',
      locationName:'玉渊潭公园西门',
      lat:39.9664,
      lng:116.4016,
      search:['夜跑','玉渊潭','跑步','户外'].join(' ')
    },
    {
      id:'wedding-1',
      type:'wedding',
      title:'婚庆协助｜全天｜海淀区',
      price:500,
      timeKey:'future',
      timeText:'4月28日 07:30',
      duration:'全天',
      credit:90,
      statusClass:'pending',
      statusText:'',
      insuranceClass:'uninsured',
      insuranceText:'未购保险',
      badgeText:'',
      tags:[],
      publisher:'赵同学',
      locationName:'海淀逸林酒店',
      lat:39.9483,
      lng:116.3781,
      search:['婚庆','伴娘','酒店','婚礼'].join(' ')
    },
    {
      id:'health-3',
      type:'health',
      title:'健康陪诊｜4 小时｜东城区',
      price:220,
      timeKey:'future',
      timeText:'4月24日 08:30',
      duration:'约4h',
      credit:93,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'宋先生',
      locationName:'北京协和医院东院区',
      lat:39.9308,
      lng:116.3921,
      search:['陪诊','协和','医院','国际部'].join(' ')
    },
    {
      id:'cat-4',
      type:'cat',
      title:'上门喂猫｜45 分钟/次｜通州区',
      price:210,
      timeKey:'future',
      timeText:'4月30日 18:30',
      duration:'约45分钟/次',
      credit:89,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'林女士',
      locationName:'通州万达旁合租公寓',
      lat:39.9132,
      lng:116.4556,
      search:['喂猫','通州','视频','连单'].join(' ')
    },
    {
      id:'wedding-2',
      type:'wedding',
      title:'婚庆协助｜半天｜朝阳区',
      price:420,
      timeKey:'future',
      timeText:'5月10日 08:00',
      duration:'半天',
      credit:78,
      statusClass:'closed',
      statusText:'已结束归档',
      insuranceClass:'uninsured',
      insuranceText:'未购保险',
      badgeText:'',
      tags:[],
      publisher:'孙先生',
      locationName:'朝阳宴会艺术中心',
      lat:39.9174,
      lng:116.4412,
      search:['婚庆','迎宾','婚礼','流程'].join(' ')
    },
    {
      id:'gz-outdoor-1',
      type:'outdoor',
      title:'户外任务｜1.5 小时｜天河区',
      price:128,
      timeKey:'tomorrow',
      timeText:'明天 19:30',
      duration:'约1.5h',
      credit:87,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'阿杰',
      locationName:'花城广场海心桥口',
      lat:23.1216,
      lng:113.3278,
      search:['广州','珠江','夜跑','花城广场','陪跑'].join(' ')
    },
    {
      id:'gz-health-1',
      type:'health',
      title:'健康陪诊｜3 小时｜越秀区',
      price:166,
      timeKey:'week',
      timeText:'周五 09:20',
      duration:'约3h',
      credit:91,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'叶阿姨',
      locationName:'中山一院门诊楼',
      lat:23.1258,
      lng:113.2966,
      search:['广州','陪诊','医院','中山一院'].join(' ')
    },
    {
      id:'gz-cat-1',
      type:'cat',
      title:'上门喂猫｜50 分钟/次｜天河区',
      price:138,
      timeKey:'future',
      timeText:'4月26日 18:00',
      duration:'约50分钟/次',
      credit:88,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'罗小姐',
      locationName:'体育西路公寓',
      lat:23.1341,
      lng:113.3289,
      search:['广州','喂猫','英短','体育西'].join(' ')
    },
    {
      id:'gz-outdoor-2',
      type:'outdoor',
      title:'户外任务｜3.5 小时｜白云区',
      price:188,
      timeKey:'future',
      timeText:'5月02日 06:40',
      duration:'约3.5h',
      credit:90,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'周生',
      locationName:'白云山南门游客中心',
      lat:23.1652,
      lng:113.2898,
      search:['广州','白云山','爬山','陪同'].join(' ')
    },
    {
      id:'hs-outdoor-1',
      type:'outdoor',
      title:'户外任务｜8 小时｜黄山区',
      price:360,
      timeKey:'future',
      timeText:'5月18日 06:30',
      duration:'约8h',
      credit:93,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'热门',
      tags:[],
      publisher:'郑先生',
      locationName:'黄山风景区换乘中心',
      lat:30.1336,
      lng:118.1741,
      search:['黄山','爬山','下个月','陪爬','登山','风景区'].join(' ')
    },
    {
      id:'hs-outdoor-2',
      type:'outdoor',
      title:'户外任务｜10 小时｜黄山区',
      price:420,
      timeKey:'future',
      timeText:'5月23日 04:50',
      duration:'约10h',
      credit:94,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'林先生',
      locationName:'黄山北大门停车场',
      lat:30.1657,
      lng:118.1851,
      search:['黄山','日出','爬山','北海','陪同'].join(' ')
    },
    {
      id:'hs-health-1',
      type:'health',
      title:'健康陪诊｜2.5 小时｜屯溪区',
      price:158,
      timeKey:'future',
      timeText:'4月27日 09:00',
      duration:'约2.5h',
      credit:86,
      statusClass:'reserve',
      statusText:'可接单',
      insuranceClass:'insured',
      insuranceText:'已购保险',
      badgeText:'',
      tags:[],
      publisher:'程阿姨',
      locationName:'黄山市人民医院',
      lat:29.7234,
      lng:118.3186,
      search:['黄山','医院','陪诊','人民医院'].join(' ')
    },
    {
      id:'hs-cat-1',
      type:'cat',
      title:'上门喂猫｜1 小时｜屯溪区',
      price:126,
      timeKey:'future',
      timeText:'4月29日 17:30',
      duration:'约1h',
      credit:82,
      statusClass:'open',
      statusText:'可接单',
      insuranceClass:'uninsured',
      insuranceText:'未购保险',
      badgeText:'',
      tags:[],
      publisher:'吴同学',
      locationName:'屯溪老街民宿',
      lat:29.7121,
      lng:118.3091,
      search:['黄山','屯溪','老街','喂猫'].join(' ')
    }
  ];

  function getLocationById(id){
    return locations.find(function(item){return item.id===id;})||null;
  }

  function distanceKm(from,to){
    const rad=Math.PI/180;
    const dLat=(to.lat-from.lat)*rad;
    const dLng=(to.lng-from.lng)*rad;
    const lat1=from.lat*rad;
    const lat2=to.lat*rad;
    const a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)*Math.sin(dLng/2);
    return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
  }

  function searchLocations(query){
    const keyword=(query||'').trim().toLowerCase();
    if(!keyword){
      return locations.slice();
    }
    return locations
      .map(function(item){
        const haystack=[item.name,item.shortName,item.city,item.district,item.region].concat(item.keywords||[]).join(' ').toLowerCase();
        const score=(item.name.toLowerCase().indexOf(keyword)===0?4:0)+(item.shortName.toLowerCase().indexOf(keyword)===0?3:0)+(haystack.indexOf(keyword)>-1?1:0);
        return {item:item,score:score};
      })
      .filter(function(entry){return entry.score>0;})
      .sort(function(a,b){return b.score-a.score;})
      .map(function(entry){return entry.item;});
  }

  window.BANXING_DATA={
    defaultCurrentLocationId:'current-beijing-haidian',
    locations:locations,
    tasks:tasks,
    getLocationById:getLocationById,
    distanceKm:distanceKm,
    searchLocations:searchLocations
  };
})();
